announce = false
debug = true
description = 'example description'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'de'
modules = [ 'js-module' ]
name = 'example server'
players = 1024
port = 7788
resources = [ 'core' ]
tags = []
website = 'example.com'